### ISSUE TITLE
How can I get the status updates

### ISSUE THREAD

**Issue by hpposch** [Smarteon/loxone-java#20]
Hello, I use your code to control some of my Loxone components.
Everything works fine for me, the only thing I am missing is the status updates.
How can I enable them?

This is my initialization code:
`
Security.addProvider(new BouncyCastleProvider());
		
		LoxoneHttp loxoneHttp = new LoxoneHttp(address, port);
		LoxoneWebSocket loxoneWebSocket = new LoxoneWebSocket(address, new LoxoneAuth(loxoneHttp, user, password, password));
		loxoneConfig = loxoneHttp.get(Protocol.C_APP, loxoneWebSocket.getLoxoneAuth(), LoxoneConfig.class);
		
		loxoneWebSocket.registerListener(new LxCommandListener());
		loxoneWebSocket.registerListener(new LxEventListener());
`

I expect that one of the listeners I have registered should automatically get the updates, but nothing happens.

**Comment by hpposch** [comment]
This is the exception I get: 

`
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
jdev/sys/keyexchange/pCQafKoJqeo8Hqgex3VxBYTLG5qxeSmwQdYlxUHTe+1WwxAGf2BfX8cqNaIcn195VuVMj9Mt+ruakEggnNYfSU/WFF/Ov9AQ96/jecUZb/4fb1Fb8iC/ezw63Zsq6/Pzc+OIXfZB2a4xprGyXf18qvYR8aBN1rAfcjs61XbfSv4=
cz.smarteon.loxone.message.JsonValue@2fce81cc
Got answer on command=jdev/sys/keyexchange/pCQafKoJqeo8Hqgex3VxBYTLG5qxeSmwQdYlxUHTe+1WwxAGf2BfX8cqNaIcn195VuVMj9Mt+ruakEggnNYfSU/WFF/Ov9AQ96/jecUZb/4fb1Fb8iC/ezw63Zsq6/Pzc+OIXfZB2a4xprGyXf18qvYR8aBN1rAfcjs61XbfSv4= value=cz.smarteon.loxone.message.JsonValue@2fce81cc
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Error of loxone connection
cz.smarteon.loxone.LoxoneException: Can't perform AES encryption
	at cz.smarteon.loxone.LoxoneAuth.encryptWithSharedKey(LoxoneAuth.java:344)
	at cz.smarteon.loxone.LoxoneAuth.encryptCommand(LoxoneAuth.java:224)
	at cz.smarteon.loxone.LoxoneWebSocket.processCommand(LoxoneWebSocket.java:298)
	at cz.smarteon.loxone.LoxoneWebSocket.processMessage(LoxoneWebSocket.java:222)
	at cz.smarteon.loxone.LoxoneWebsocketClient.onMessage(LoxoneWebsocketClient.java:74)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:462)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:389)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at cz.smarteon.loxone.LoxoneAuth.encryptWithSharedKey(LoxoneAuth.java:340)
	... 10 more
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed 
[main] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
`

**Comment by jimirocks** [comment]
Hi, thanks for report.

1. The listeners work only when the websocket is connected which is not after `LoxoneWebSocket` construction - since the connection is lazy, pls try first call some `sendCommand`
2. Currently only TEXT and VALUE events [are supported](https://github.com/Smarteon/loxone-java/blob/828ef9180e816dd1874d721bbf4c0d80724b99cc/src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java#L229), so it's possible that your event is of different type (we will be happy to accept pull requests with modifications for other types)
3. From your exception it looks like you have some problem with AES - can you check whether you have AES cipher available at your JRE? (ie those from oracle need to install additional package with security extensions)

**Comment by hpposch** [comment]
Hi, thank you for your quick answer :)

To 1.: so I only have to do something like this:
`
Security.addProvider(new BouncyCastleProvider());
		
		LoxoneHttp loxoneHttp = new LoxoneHttp(address, port);
		LoxoneWebSocket loxoneWebSocket = new LoxoneWebSocket(address, new LoxoneAuth(loxoneHttp, user, password, password));
		loxoneConfig = loxoneHttp.get(Protocol.C_APP, loxoneWebSocket.getLoxoneAuth(), LoxoneConfig.class);
		
		loxoneWebSocket.sendCommand(Protocol.C_APP);
		
		loxoneWebSocket.registerListener(new LxCommandListener());
		loxoneWebSocket.registerListener(new LxEventListener());
`

To 2.: Thats fine for me

To 3.: How can I check this, or what do I need to install?

**Comment by hpposch** [comment]
Because when I try your example I get the same exception, so I guess I am missing the thing you mentioned in 3.

**Comment by jimirocks** [comment]
Put some breakpoint [here](https://github.com/Smarteon/loxone-java/blob/fa8ae07bdbc26cb1a41003affbf1b82ff90a0058/src/main/java/cz/smarteon/loxone/LoxoneAuth.java#L344) and investigate the caught exception there. Also please send us the `java -version` output. I the vendor is oracle you can try install JCE (ie [here for JDK8](https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html))

**Comment by hpposch** [comment]
I get the following exception: 
java.security.InvalidKeyException: Illegal key size

**Comment by hpposch** [comment]
Now the stack trace also looks a bit different:
`
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
[WebSocketConnectReadThread-14] WARN cz.smarteon.loxone.LoxoneWebSocket - No command listener registered, ignoring command=jdev/sys/keyexchange/iw6zsQgH9+5EI8GCohxtD8ndXGgaZUsIGVeshTjdEnVIgC+8fCIQip3Hu/mvHCVG9m+Sp4mmgy/XZb+gIRthSHu3ZXN2Ft/H0PnY1Jno69owiqL0GzeIDfmxAn2L0gQgyhVc/Kd7vFH4jttRb2tsW7kwjD/GnzdJyqtG8YbAoa8=
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Error of loxone connection
cz.smarteon.loxone.LoxoneException: Can't perform AES encryption
	at cz.smarteon.loxone.LoxoneAuth.encryptWithSharedKey(LoxoneAuth.java:344)
	at cz.smarteon.loxone.LoxoneAuth.encryptCommand(LoxoneAuth.java:224)
	at cz.smarteon.loxone.LoxoneWebSocket.processCommand(LoxoneWebSocket.java:298)
	at cz.smarteon.loxone.LoxoneWebSocket.processMessage(LoxoneWebSocket.java:222)
	at cz.smarteon.loxone.LoxoneWebsocketClient.onMessage(LoxoneWebsocketClient.java:74)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:462)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:389)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at cz.smarteon.loxone.LoxoneAuth.encryptWithSharedKey(LoxoneAuth.java:340)
	... 10 more
[WebSocketConnectReadThread-14] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed 
[main] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
`

**Comment by jimirocks** [comment]
So the JRE is oracle one, have JCE installed? If not I suppose it will solve the issue, otherwise this may be a BUG, then pls try OpenJDK (which should have cryptography extensions included)

**Comment by hpposch** [comment]
Yes I think I have installed it, I have a Mac and I am not sure if it is the correct location, but I had a look at a older installed version and there I saw the files in the same directory, so I guess it is installed correctly.

I will now try it on windows with OpenJDK and give you a feedback if this works.

**Comment by hpposch** [comment]
I have tested it now with OpenJDk on windows and it works for me.
Thank you :)
Really a great piece of software!!!

**Comment by jimirocks** [comment]
Thanks for feedback, I am glad it works at least on windows. I suppose the issue on MAC has something to do with accessibility of AES in JRE there. Would be nice if you have time to investigate it more and figure out what's the problem, otherwise I will file a new BUG and will try to investigate later (since I have no MAC to play with right now)

**Comment by hpposch** [comment]
I am very busy at the moment, but i will take some time to investigate on this issue later :)
For the moment i have to deliver some new software parts..

**Comment by jimirocks** [comment]
Closing for inacivity, feel free to open another issue in case of problem on Apple's OS
